latitude: -71.413177
longitude: 21.144019
openweather_api_token: 3lc7bnsiutp6iypfmi26lt9b40fdi1bv
openweather_base_url: https://api.openweathermap.org
gotify_base_url: https://gotify.example.com
gotify_app_token: A39e9qdjd.sdf9
log_path: /tmp
